### ISSUE TITLE
Connection settings, looks like it's emulating a 10.8.2 desktop

### ISSUE THREAD

**Issue by mdp** [mdp/iMessageChatDecompile#2]
Also, seems like an odd string to hardcode
https://github.com/mdp/iMessageChatDecompile/blob/master/smali/com/b/x.smali#L1171

**Comment by BeauGiles** [comment]
Odd indeed.

> I can tell you exactly what it is. Our Hacs are not sending a valid x-ds-client-id to the iMessage service. The x-ds-client-id is a 40 character hexadecimal number, and it is unique to a device. It is not the same as the UUID, the serial number, or the MAC addresses of network interfaces that are active.

http://www.tonymacx86.com/general-help/84047-solved-updated-imessage-wont-work-8.html
